version: 1.0.{build}
before_build:
  - source\Thinktecture.IdentityServer.Services.Contrib\nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: di77CstF0jvvy/vMgIrYsvrL8ErTWxKbAImcUDdUERD/Zosdta7uM07XuW19vweY
  artifact: /.*\.nupkg/
