version: 0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
  - cmd: nuget restore source\Contrib.sln\Contrib.sln
build:
  project: source\Contrib.sln\Contrib.sln  
  publish_nuget: true
  verbosity: minimal
before_build:
- ps: updatenuspecversion.ps1
deploy:
  provider: NuGet
  api_key:
    secure: di77CstF0jvvy/vMgIrYsvrL8ErTWxKbAImcUDdUERD/Zosdta7uM07XuW19vweY
  artifact: /.*\.nupkg/
