version: 1.0.{build}

install:
  - cmd: nuget restore source\Thinktecture.IdentityServer.Services.Contrib\packages.config -SolutionDirectory .
build:
  project: source/Contrib.sln  
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: di77CstF0jvvy/vMgIrYsvrL8ErTWxKbAImcUDdUERD/Zosdta7uM07XuW19vweY
  artifact: /.*\.nupkg/
